spring:
    datasource:
        url: jdbc:postgresql://localhost:5432/food_truck_db
        username: admin_user
        password:
flyway:
    user: admin_user
    password: 1234
server:
    error:
        include-message: always